stages:
  - Build
  - Test
  - MockTest


Building:
  stage: Build
  script:
    - ./req_ubuntu.sh
    - ./build.sh

Testing:
  stage: Test
  script:
    - ./req_ubuntu.sh
    - ./build.sh --test
    - ./Tests.out --gtest_output=xml:TestsRes.xml
  artifacts:
    name: 'TestsRes'
    paths:
      - TestsRes.xml


MockTesting:
  stage: MockTest
  script:
    - ./req_ubuntu.sh
    - ./build.sh --mock-test
    - ./MockTest.out --gtest_output=xml:MockTestRes.xml
  artifacts:
    name: 'MockTestRes'
    paths:
      - MockTestRes.xml


