stages:
  - Build
  - Test
  - MockTest


Building:
  stage: Build
  script:
    - ./req_ubuntu.sh
    - ./build.sh

Testing:
  stage: Test
  script:
    - ./req_ubuntu.sh
    - ./build.sh --test
    - ./bin/Test.out


MockTesting:
  stage: MockTest
  script:
    - ./req_ubuntu.sh
    - ./build.sh --mock-test
    - ./bin/MockTest.out

